language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - develop

scripts : 
  - npm run test

notifications:
  email:
    recipients:
    - bennybenester@gmail.com
    on_success: change
    on_failure: always